version: '3.8'

services:
  web:
    build: .
    container_name: vk_web
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: vk_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vkontakte
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      DB_HOST: db
    ports:
      - "3308:3306"        # порт 3307, чтобы не конфликтовать с XAMPP
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
